import { describe, expect, it } from "vitest";

import { generateThemeCss } from "../../src/styles/generateThemeAssets";

const SAMPLE_TOKENS = [
  {
    id: "surface-primary",
    role: "surface",
    value: { type: "color", hex: "#1A73E8" },
    contrast: { high: { type: "color", hex: "#0B1B33" } }
  },
  {
    id: "text-body-default",
    role: "text",
    value: { type: "color", hex: "#1F2933" },
    contrast: { high: { type: "color", hex: "#FFFFFF" } }
  }
] as const;

describe("theme CSS generation", () => {
  it("generates standard and high-contrast CSS variable declarations", () => {
    const css = generateThemeCss({ tokens: SAMPLE_TOKENS });

    expect(css).toMatchInlineSnapshot(`
/**
 * DO NOT EDIT DIRECTLY
 * Generated by packages/shared/src/styles/generateThemeAssets.ts
 */
:root {
  --surface-primary: #1A73E8;
  --text-body-default: #1F2933;
}

[data-theme="contrast"] {
  --surface-primary: #0B1B33;
  --text-body-default: #FFFFFF;
}
`);
  });
});
