name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "004-add-css-formatting"
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint and style checks
        run: npm run lint
        env:
          LINT_SKIP_ENFORCEMENT: "true"

      - name: Verify formatter output
        run: npm run format:css -- --check

      - name: Compile Tailwind layers
        run: npm run tailwind:build -- --ci

      - name: Run unit tests
        run: npm run test
